<?php
$this->renderPart('mainHeader');
$this->renderPart('mainNavigation');
?>

    <div class="col d-flex flex-column h-sm-100">
        <div class="content">
            <div class="col-12 box">
                <div class="boxheader">Alle interne Mitarbeiter</div>
                <div class="boxbody">
                    <table class="table table-borderless table_main">
                        <thead>
                        <tr>
                            <th scope="col">MitarbeiterNummer</th>
                            <th scope="col">Vorname</th>
                            <th scope="col">Nachname</th>
                            <th scope="col">Straße</th>
                            <th scope="col">PLZ</th>
                            <th scope="col">Ort</th>
                            <th scope="col">Telefon</th>
                            <th scope="col">E-Mail</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->__get('interneMitarbeiter') as $mitarbeiter) { ?>
                            <tr>
                                <th scope="row"><?= $mitarbeiter->getMitarbeiterID() ?></th>
                                <td><b><?= $mitarbeiter->getVorname() ?></b></td>
                                <td><b><?= $mitarbeiter->getNachname() ?></b></td>
                                <td><b><?= $mitarbeiter->getStrasse() ?></b></td>
                                <td><b><?= $mitarbeiter->getPlz() ?></b></td>
                                <td><b><?= $mitarbeiter->getOrt() ?></b></td>
                                <td><b><?= $mitarbeiter->getTelefon() ?></b></td>
                                <td><b><?= $mitarbeiter->getEmail() ?></b></td>

                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>


                </div>
                <div class="boxfooter"></div>
            </div>

            <div class="col-12 box">
                <div class="boxheader">Alle externe Mitarbeiter</div>
                <div class="boxbody">
                    <table class="table table-borderless table_main">
                        <thead>
                        <tr>
                            <th scope="col">MitarbeiterNummer</th>
                            <th scope="col">Vorname</th>
                            <th scope="col">Nachname</th>
                            <th scope="col">Straße</th>
                            <th scope="col">PLZ</th>
                            <th scope="col">Ort</th>
                            <th scope="col">Telefon</th>
                            <th scope="col">E-Mail</th>
                            <th scope="col">Firma</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->__get('externeMitarbeiter') as $mitarbeiter) { ?>
                            <tr>
                                <th scope="row"><?= $mitarbeiter->getMitarbeiterID() ?></th>
                                <td><b><?= $mitarbeiter->getVorname() ?></b></td>
                                <td><b><?= $mitarbeiter->getNachname() ?></b></td>
                                <td><b><?= $mitarbeiter->getStrasse() ?></b></td>
                                <td><b><?= $mitarbeiter->getPlz() ?></b></td>
                                <td><b><?= $mitarbeiter->getOrt() ?></b></td>
                                <td><b><?= $mitarbeiter->getTelefon() ?></b></td>
                                <td><b><?= $mitarbeiter->getEmail() ?></b></td>
                                <td><b><?= $mitarbeiter->getName() ?></b></td>

                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>


                </div>
                <div class="boxfooter"></div>
            </div>


        </div>

    </div>

<?php
$this->renderPart('mainFooter');
?>