<?php
$this->renderPart('mainHeader');
$this->renderPart('mainNavigation');
?>

    <div class="col d-flex flex-column h-sm-100">
        <div class="content">

            <div class="col-12 box">
                <div class="boxheader">Mitarbeiter Nummer</div>
                <div class="boxbody">


                    <form class="row g-3" method="post">

                        <div class="col-md-3">
                            <label for="inputCity" class="form-label">Mitarbeiternummer:</label>
                            <input type="text" class="form-control form-control-sm" id="inputCity" name="id"
                                   required>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary graybutton">Anzeigen</button>
                        </div>
                    </form>

                </div>
                <div class="boxfooter"></div>
            </div>


            <div class="col-12 box">


                <div class="boxheader">
                    <?php
                    if ($this->__get('Mitarbeiter')[0]->getMitarbeiterID() == NULL) { ?> Mitarbeiter wurde nicht gefunden <?php } else { ?>
                    Mitarbeiter mit der
                    Mitarbeiter Nummer: <?= $this->__get('Mitarbeiter')[0]->getMitarbeiterID() ?></div>
                <div class="boxbody">
                    <table class="table table-borderless table_main">
                        <thead>
                        <tr>
                            <th scope="col">Vorname</th>
                            <th scope="col">Nachname</th>
                            <th scope="col">Straße</th>
                            <th scope="col">PLZ</th>
                            <th scope="col">Ort</th>
                            <th scope="col">Telefon</th>
                            <th scope="col">E-Mail</th>
                            <th scope="col">Firma</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            <td><b><?= $this->__get('Mitarbeiter')[0]->getVorname() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getNachname() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getStrasse() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getPlz() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getOrt() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getTelefon() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getEmail() ?></b></td>
                            <td><b><?= $this->__get('Mitarbeiter')[0]->getName() ?></b></td>
                            <?php } ?>
                        </tr>
                        </tbody>
                    </table>


                </div>
                <div class="boxfooter"></div>
            </div>


        </div>

    </div>

<?php
$this->renderPart('mainFooter');
?>